# Generated by Django 3.1.4 on 2020-12-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gmail', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
