# Generated by Django 3.1.4 on 2020-12-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proc_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate_Proc',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gmail', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('Gaze_Score', models.IntegerField()),
            ],
        ),
    ]
